// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44341' | (string & {});
};

export type SchemaFolder = {
    id: string;
    name: string;
    parentId?: string | null;
};

export type SchemaGraph = {
    generatedAt: string;
    folders: Array<SchemaFolder>;
    nodes: Array<SchemaNode>;
};

export type SchemaNode = {
    id: string;
    alias: string;
    name: string;
    icon: string;
    iconColor?: string | null;
    folderId?: string | null;
    isElement: boolean;
    allowedAsRoot: boolean;
    variesByCulture: boolean;
    variesBySegment: boolean;
    description?: string | null;
    ownPropertyCount: number;
    composedPropertyCount: number;
    templates: Array<SchemaTemplate>;
};

export type SchemaTemplate = {
    id: string;
    alias: string;
    name: string;
    isDefault: boolean;
};

export type GraphData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/schema-city/graph';
};

export type GraphErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GraphResponses = {
    /**
     * OK
     */
    200: SchemaGraph;
};

export type GraphResponse = GraphResponses[keyof GraphResponses];
